### ISSUE TITLE
matcher syntax and api

### ISSUE THREAD

**Issue by autopp** [autopp/spexec#1]
status code, stdout and stderr should be checked by some matcher
```yaml
expect:
  status:
    - success: true
  stdout:
    - contain: "42"
    - match: "^answer is"
```

matcher should be interface in Go.
```go
type Matcher interface {
  // some methods
}

type Success struct {} // implements Matcher
```
